name: Mario H. Gonzalez-Sauri
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

kramdown:
  input: GFM
  hard_wrap: False
  syntax_highlighter: rouge
  syntax_highlighter_opts: {span: {disable: true}
